[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
